config/routes.rb
Rails.application.routes.draw do
  get 'hardware/cpu', to: "hardware#cpu", as: 'cpu_mod'
  get 'hardware/gpu', to: "hardware#gpu", as: 'gpu_mod'
  get 'hardware/motherboard', to: "hardware#motherboard", as: 'motherboard_mod'
  get 'hardware/memory', to: "hardware#memory", as: 'memory_mod'
  get 'hardware/psu', to: "hardware#psu", as: 'psu_mod'
  get 'hardware/disk', to: "hardware#disk", as: 'disk_mod'
  get 'hardware/cooler', to: "hardware#cooler", as: 'cooler_mod'
  get 'foradmin/manip_users'
  get 'foradmin/manip_hardware', to: "foradmin#manip_hardware", as: 'manip_hardware'
  devise_for :users
  get 'pages/welcome'
  get 'pages/configuration', to: "pages#configuration", as: 'configurator'
  get 'pages/observation', to: "pages#observation", as: 'observation'
  delete "pages/delete_pc/:id", to: "pages#delete_pc", as: 'delete_pc'
  delete "foradmin/delete_user/:id", to: "foradmin#delete_user", as: 'delete_user'
  post 'hardware/cpu', to: 'hardware#create_cpu', as: 'create_cpu'
  delete "hardware/delete_cpu/:id", to: "hardware#delete_cpu", as: 'delete_cpu'
  post 'hardware/gpu', to: 'hardware#create_gpu', as: 'create_gpu'
  delete "hardware/delete_gpu/:id", to: "hardware#delete_gpu", as: 'delete_gpu'
  post 'hardware/motherboard', to: 'hardware#create_motherboard', as: 'create_motherboard'
  delete "hardware/delete_motherboard/:id", to: "hardware#delete_motherboard", as: 'delete_motherboard'
  post 'hardware/memory', to: 'hardware#create_memory', as: 'create_memory'
  delete "hardware/delete_memory/:id", to: "hardware#delete_memory", as: 'delete_memory'
  post 'hardware/psu', to: 'hardware#create_psu', as: 'create_psu'
  delete "hardware/delete_psu/:id", to: "hardware#delete_psu", as: 'delete_psu'
  post 'hardware/disk', to: 'hardware#create_disk', as: 'create_disk'
  delete "hardware/delete_disk/:id", to: "hardware#delete_disk", as: 'delete_disk'
  post 'hardware/cooler', to: 'hardware#create_cooler', as: 'create_cooler'
  delete "hardware/delete_cooler/:id", to: "hardware#delete_cooler", as: 'delete_cooler'
  post "pages/configuration", to: "pages#creation"
  get "pages/show_pc/:id", to: "pages#show_pc", as: 'show_pc'
  patch "pages/ru", to: "pages#ru", as: 'ru'
  patch "pages/eng", to: "pages#en", as: 'eng'
  get "pages/send_computers", to: "pages#send_computers", as: 'comp_mail'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#welcome"
end

app/views/pages/configuration.html.erb
<div class="content">
	<header>
		<% if current_user %>
			<% if current_user.admin %>
				<div style="margin-left: 50px; padding-top: 50px; font-size: 30px; float: left;" class="regular_text"><%= t :cur_user %>: <%= t :admin %></div>
			<% else %>
				<div style="margin-left: 50px; padding-top: 50px; font-size: 30px; float: left;" class="regular_text"><%= t :cur_user %>: <%= current_user.email %></div>
			<% end %>
			<img src="/HeaderIcon.png" style="position: absolute; left: 750px;">
			<div style="text-align: right; margin-right: 50px; padding-top: 40px; float: right;"><%= button_to t(:log_out), destroy_user_session_path, data: { turbo: false }, method: :delete, :id=>"signoutbut" %></div>
		<% end %>
	</header>
	<div class="rightsidebar">
		<%= button_to t(:home), root_path, method: :get, :class => "rightsidebarlinks" %></br>
		<%= button_to t(:my_comp), observation_path, method: :get, :class => "rightsidebarlinks" %></br>
	</div>
	<div class="leftsidebar"></div>
	<%= form_with do |form| %>
	<div style="width: 360px; height: 130px; float: left; margin-top: 20px; margin-left: 25px; background: rgba(0,0,0,0.3); border-radius: 4px;">
		<div style="border: 1px solid transparent; margin: auto; width: 100%;">
			<img src="/cpu_icon.png" style="float: left; margin-top: 10px; margin-left: 40px;">
			<p style="float: left; color: white; font-size: 32px; margin-top: 24px; margin-left: 10px;"><%= t :cpu %></p>
		</div>
		<%= select_tag(:cpu, options_for_select(cpu_array), {include_blank: true, :class => "select"}) %>
	</div>
	<div style="width: 485px; height: 130px; float: left; margin-top: 20px; margin-left: 30px; background: rgba(0,0,0,0.3); border-radius: 4px;">
		<div style="border: 1px solid transparent; margin: auto; width: 100%;">
			<img src="/gpu_icon.png" style="float: left; margin-top: 10px; margin-left: 40px;">
			<p style="float: left; color: white; font-size: 32px; margin-top: 24px; margin-left: 10px"><%= t :gpu %></p>
		</div>
		<%= select_tag(:gpu, options_for_select(gpu_array), {include_blank: true, :class => "select"}) %>
	</div>
	<div style="width: 470px; height: 130px; float: left; margin-top: 20px; margin-left: 30px; background: rgba(0,0,0,0.3); border-radius: 4px;">
		<div style="border: 1px solid transparent; margin: auto; width: 100%;">
			<img src="/mb_icon.png" style="float: left; margin-left: 40px; margin-top: 10px">
			<p style="float: left; color: white; font-size: 32px; margin-top: 24px; margin-left: 10px;"><%= t :motherboard %></p>
		</div>
		<%= select_tag(:motherboard, options_for_select(motherboard_array), {include_blank: true, :class => "select"}) %>
	</div>
	<div style="width: 360px; height: 130px; float: left; margin-top: 20px; margin-left: 25px; background: rgba(0,0,0,0.3); border-radius: 4px;">
		<div style="border: 1px solid transparent; margin: auto; width: 100%;">
			<img src="/psu_icon.png" style="float: left; margin-left: 40px; margin-top: 10px">
			<p style="float: left; color: white; font-size: 32px; margin-top: 24px; margin-left: 10px;"><%= t :psu %></p>
		</div>
		<%= select_tag(:psu, options_for_select(psu_array), {include_blank: true, :class => "select"}) %>
	</div>
	<div style="width: 220px; height: 130px; float: left; margin-top: 20px; margin-left: 30px; background: rgba(0,0,0,0.3); border-radius: 4px;">
		<div style="border: 1px solid transparent; margin: auto; width: 100%;">
			<img src="/disk_icon.png" style="float: left; margin-left: 40px; margin-top: 10px">
			<p style="float: left; color: white; font-size: 32px; margin-top: 24px; margin-left: 10px;"><%= t :disk %></p>
		</div>
		<%= select_tag(:disk, options_for_select(disk_array), {include_blank: true, :class => "select"}) %>
	</div>
	<div style="width: 235px; height: 130px; float: left; margin-top: 20px; margin-left: 30px; background: rgba(0,0,0,0.3); border-radius: 4px;">
		<div style="border: 1px solid transparent; margin: auto; width: 100%;">
			<img src="/cooler_icon.png" style="float: left; margin-left: 35px; margin-top: 10px">
			<p style="float: left; color: white; font-size: 32px; margin-top: 24px; margin-left: 10px;"><%= t :cooler %></p>
		</div>
		<%= select_tag(:cooler, options_for_select(cooler_array), {include_blank: true, :class => "select"}) %>
	</div>
	<div style="width: 470px; height: 130px; float: left; margin-top: 20px; margin-left: 30px; background: rgba(0,0,0,0.3); border-radius: 4px;">
		<div style="border: 1px solid transparent; margin: auto; width: 100%;">
			<img src="/mem_icon.png" style="float: left; margin-left: 40px; margin-top: 10px">
			<p style="float: left; color: white; font-size: 32px; margin-top: 24px; margin-left: 10px;"><%= t :memory %></p>
		</div>
		<%= select_tag(:memory, options_for_select(memory_array), {include_blank: true, :class => "mem_select", :style => "margin-left: 5px;"}) %>
		<%= number_field_tag :memory_number, '2', in: 1..8, class: "num_input" %>
	</div>
	<%= form.submit t(:build), :class => "build" %>
	<% end %>
	<p class="notice" style="float: left; margin-left: 30px; color: red; font-size: 30px;"><%= notice %></p>
	<img src="/examp.png" style="position: absolute; left: 680px; top: 520px; height: 450px; width: auto;" >
</div>

app/views/pages/info_first.html.erb
<div>Новый текст</div>

app/views/pages/observation.html.erb
<div class="content">
	<header>
		<% if current_user %>
			<% if current_user.admin %>
				<div style="margin-left: 50px; padding-top: 50px; font-size: 30px; float: left;" class="regular_text"><%= t :cur_user %>: <%= t :admin %></div>
			<% else %>
				<div style="margin-left: 50px; padding-top: 50px; font-size: 30px; float: left;" class="regular_text"><%= t :cur_user %>: <%= current_user.email %></div>
			<% end %>
			<img src="/HeaderIcon.png" style="position: absolute; left: 750px;">
			<div style="text-align: right; margin-right: 50px; padding-top: 40px; float: right;"><%= button_to t(:log_out), destroy_user_session_path, data: { turbo: false }, method: :delete, :id=>"signoutbut" %></div>
		<% end %>
	</header>
	<div class="rightsidebar">
		<%= button_to t(:home), root_path, method: :get, :class => "rightsidebarlinks" %></br>
		<%= button_to t(:conf), configurator_path, method: :get, :class => "rightsidebarlinks" %></br>	
	</div>
	<div class="leftsidebar"></div>
	<% if Computer.where(User_id: current_user.id).count == 0%>
		<p id="sad"><%= t :sad_notice %></p>
	<% else %>
		<table>
		  <thead>
		    <tr>
		      	<th><%= t :cpu %></th>
		      	<th><%= t :gpu %></th>
		      	<th><%= t :motherboard %></th>
				<th><%= t :memory %></th>
				<th><%= t :mod_num %></th>
				<th><%= t :psu %></th>
				<th><%= t :disk %></th>
				<th><%= t :cooler %></th>
				<th><%= t :price %></th>
		      	<th></th>
		      	<th></th>
		    </tr>
		  </thead>
		  <tbody>
		    <% Computer.where(User_id: current_user.id).each do |x| %>
		    <% cur_cpu = Cpu.find_by_id(x.cpu_id) %>
		    <% cur_gpu = Videocard.find_by_id(x.videocard_id) %>
		    <% cur_mb = Motherboard.find_by_id(x.motherboard_id) %>
		    <% cur_mem = Memory.find_by_id(x.memory_id) %>
		    <% cur_psu = Psu.find_by_id(x.psu_id) %>
		    <% cur_disk = Disk.find_by_id(x.disk_id) %>
		    <% cur_cooler = Cooler.find_by_id(x.cooler_id) %>
		      <tr>
		          <td><%= cur_cpu.manufact + " " + cur_cpu.model %></td>
		          <td><%= cur_gpu.manufact + " " + cur_gpu.model %></td>
		          <td><%= cur_mb.name %></td>
		          <td><%= cur_mem.volume_one.to_s + " " + t(:sign_gb) + ", " + cur_mem.max_freq.to_s + " " + t(:sign_mhz) %></td>
			      <td><%= x.memory_num %></td>
			      <td><%= cur_psu.wattage.to_s + " " + t(:sign_w) + ", " + cur_psu.certificate %></td>
			      <td><%= cur_disk.storage_type + ", " + cur_disk.volume.to_s + " " + t(:sign_tb) %></td>
			      <td><%= cur_cooler.tdp.to_s + " " + t(:sign_w) %></td>
			      <td><%= x.total_price.to_s + " ₽"  %></td>
		          <td><%= button_to t(:show), show_pc_path(x), method: :get %></td>
		          <td><%= button_to t(:delete), delete_pc_path(x), method: :delete %></td>
		      </tr>
		    <% end %>
		  </tbody>
		</table>
	<% end %>
</div>

app/views/pages/welcome.html.erb
<div class="content">
	<header>
	<% if current_user %>
		<% if current_user.admin %>
			<div style="margin-left: 50px; padding-top: 50px; font-size: 30px; float: left;" class="regular_text"><%= t :cur_user %>: <%= t :admin %></div>
		<% else %>
			<div style="margin-left: 50px; padding-top: 50px; font-size: 30px; float: left;" class="regular_text"><%= t :cur_user %>: <%= current_user.email %></div>
		<% end %>
		<img src="HeaderIcon.png" style="position: absolute; left: 750px;">
		<div style="position: absolute; top: 48px; left: 1550px;">
			<% if I18n.locale == :ru %>
				<%= button_to "Eng", eng_path, method: :patch, :class => "localebutton" %>
				<%= button_to "Ru", {}, :disabled => true, :class => "localebutton" %>
			<% else %>
				<%= button_to "Eng", {}, :disabled => true, :class => "localebutton" %>
				<%= button_to "Ru", ru_path, method: :patch, :class => "localebutton" %>
			<% end %>
		</div>
		<div style="text-align: right; margin-right: 50px; padding-top: 40px; float: right;"><%= button_to t(:log_out), destroy_user_session_path, data: { turbo: false }, method: :delete, :id=>"signoutbut" %></div>
	<% end %>
</header>
<div class="rightsidebar">
	<%= button_to t(:conf), configurator_path, method: :get, :class => "rightsidebarlinks" %></br>
	<%= button_to t(:my_comp), observation_path, method: :get, :class => "rightsidebarlinks" %></br>
	<% if current_user.admin %>
		<%= button_to t(:man_users), foradmin_manip_users_path, method: :get, :class => "adminlinks" %></br>
		<%= button_to t(:man_hard), manip_hardware_path, method: :get, :class => "adminlinks" %></br>
	<% else %>
		<%= button_to t(:manage_account), edit_user_registration_path(current_user.id), method: :get, :class => "rightsidebarlinks" %>
	<% end %>
</div>
<div class="leftsidebar"></div>
<div style="width: 740px; height: 400px; margin-left: 600px; margin-top: 50px;">
	<% if I18n.locale == :ru %>
		<div style="border: 1px solid white; border-radius: 6px; background-color: rgba(365, 365, 365, 0.4); width: 400px; height: 296px; float: left; font-size: 18px;"><p id="educ_tab" style="margin-left: 10px; margin-right: 10px; font-family: ‘Signika’, sans-serif;">Добро пожаловать! На сайте PC Assembler вы можете создавать и сохранять сборки компьютеров, а также в любой момент посмотреть подробную информацию о любой из них.</p></div>
	<% else %>
		<div style="border: 1px solid white; border-radius: 6px; background-color: rgba(365, 365, 365, 0.4); width: 400px; height: 296px; float: left; font-size: 18px;"><p id="educ_tab" style="margin-left: 10px; margin-right: 10px; font-family: ‘Signika’, sans-serif;">Welcome! On the PC Assembler website you can create and save computers, as well as view detailed information about any of them at any time.</p></div>
	<% end %>
	<div style="width: 180px;float: left; border: 1px solid white; border-radius: 6px;">
		<% if I18n.locale == :ru %>
			<button onclick="welcome(true)" class="welcome_but"><%= t(:welcome) %>!</button>
			<button onclick="cpu(true)" class="welcome_but"><%= t(:cpu) %></button>
			<button onclick="gpu(true)" class="welcome_but"><%= t(:gpu) %></button>
			<button onclick="motherboard(true)" class="welcome_but"><%= t(:motherboard) %></button>
			<button onclick="memory(true)" class="welcome_but"><%= t(:memory) %></button>
			<button onclick="psu(true)" class="welcome_but"><%= t(:psu) %></button>
			<button onclick="disk(true)" class="welcome_but"><%= t(:disk) %></button>
			<button onclick="cooler(true)" class="welcome_but"><%= t(:cooler) %></button>
		<% else %>
			<button onclick="welcome(false)" class="welcome_but"><%= t(:welcome) %>!</button>
			<button onclick="cpu(false)" class="welcome_but"><%= t(:cpu) %></button>
			<button onclick="gpu(false)" class="welcome_but"><%= t(:gpu) %></button>
			<button onclick="motherboard(false)" class="welcome_but"><%= t(:motherboard) %></button>
			<button onclick="memory(false)" class="welcome_but"><%= t(:memory) %></button>
			<button onclick="psu(false)" class="welcome_but"><%= t(:psu) %></button>
			<button onclick="disk(false)" class="welcome_but"><%= t(:disk) %></button>
			<button onclick="cooler(false)" class="welcome_but"><%= t(:cooler) %></button>
		<% end %>
	</div>
</div>
<p class="alert" style="font-size: 28px; color: red; margin-left: 600px;"><%= alert %></p>
</div>

<script>
	function welcome(key){
	    text = document.getElementById("educ_tab")
	    if (key == true) {
			text.innerHTML = "Добро пожаловать! На сайте PC Assembler вы можете создавать и сохранять сборки компьютеров, а также в любой момент посмотреть подробную информацию о любой из них."; } 
		else {
			text.innerHTML = "Welcome! On the PC Assembler website you can create and save computers, as well as view detailed information about any of them at any time.";
		}
	}
	function cpu(key){
	    text = document.getElementById("educ_tab")
	    if (key == true) {
			text.innerHTML = "Процессор является сердцем компьютера. Он имеет множество параметров, среди которых основные: сокет, определяющий вид соединения с материнской платой, и тепловыделение, характеризующее количество тепла, которое выделяет процессор при нагрузке."; } 
		else {
			text.innerHTML = "The CPU is the heart of the computer. It has many parameters, among which the main ones are: socket, which determines the type of connection to the motherboard, and heat dissipation (TDP), which characterizes the amount of heat that the processor emits under load.";
		}
	}
	function gpu(key){
	    text = document.getElementById("educ_tab")
	    if (key == true) {
			text.innerHTML = "Видеокарта - второе сердце современного компьютера, значительно повышающее его вычислительную мощность. Важнейшим параметром видеокарты является объём: чем он выше, тем производительнее компьютер, однако важным является и поколение видеокарты."; } 
		else {
			text.innerHTML = "The videocard is the second heart of a modern computer, significantly increasing its computing power. The most important parameter of the videocard is the volume: the higher it is, the more productive the computer is, however, the generation of the video card is also important.";
		}
	}
	function motherboard(key){
	    text = document.getElementById("educ_tab")
	    if (key == true) {
			text.innerHTML = "Материнская плата - 'скелет' компьютера, который позволяет соединить все комплектующие между собой. Среди параметров стоит отметить чипсет, который определяет наличие некоторых функций."; } 
		else {
			text.innerHTML = "The motherboard is the 'skeleton' of the computer, which allows you to connect all the components together. Among the parameters, it is worth noting the chipset, which determines the presence of some functions.";
		}
	}
	function memory(key){
	    text = document.getElementById("educ_tab")
	    if (key == true) {
			text.innerHTML = "Оперативная память - память, напрямую связанная с процессором, отчего чтение с неё данных происходит почти мгновенно. При выборе оперативной памяти рядовому пользователю стоит обратить внимание на объём и частоту. Объём характеризует количество данных, одновременно хранящихся в модуле, частота показывает скорость выполнения команд."; } 
		else {
			text.innerHTML = "RAM is memory directly connected to the processor, which is why data is read from it almost instantly. When choosing RAM, an ordinary user should pay attention to the volume and frequency. The volume characterizes the amount of data stored in the module at the same time, the frequency shows the speed of command execution.";
		}
	}
	function psu(key){
	    text = document.getElementById("educ_tab")
	    if (key == true) {
			text.innerHTML = "Блок питания обеспечивает электроэнергией все компоненты компьютера. Основными характеристиками можно назвать мощность, которая показывает, насколько требовательные комлектующие вы можете использовать в сборке, и сертификат, определяющий надежность БП."; }
		else {
			text.innerHTML = "The power supply provides electricity to all components of the computer. The main characteristics can be called power, which shows how demanding components you can use in the assembly, and a certificate that determines the reliability of the PSU.";
		}
	}
	function disk(key){
	    text = document.getElementById("educ_tab")
	    if (key == true) {
			text.innerHTML = "Диск - запоминающее устройство, хранящее информацию в отсутствии питания (в противоположность оперативной памяти). Существуют разные диски, среди которых жесткие диски (HDD) - ЗУ, хранящие большой объём информации, но имеющие относительно низкую скорость чтения, и твердотельные накопители (SSD) - ЗУ, позволяющие хранить значительно меньший объём данных, чем HDD, но превосходящие их по скорости чтения. "; }
		else {
			text.innerHTML = "A disk is a storage device that stores information in the absence of power (as opposed to RAM). There are different disks, including hard disk drives (HDD) - memory, storing a large amount of information, but having a relatively low read speed, and solid-state drives (SSD) - memory, allowing you to store a much smaller amount of data than HDD, but surpassing them in read speed.";
		}
	}
	function cooler(key){
	    text = document.getElementById("educ_tab")
	    if (key == true) {
			text.innerHTML = "Кулер - элемент, позволяющий отводить тепло от процессора для поддержания его рабочей температуры. Мощность - главный параметр кулера - показывает, сколько тепла он может отвести от процессора."; }
		else {
			text.innerHTML = "Cooler is an element that allows you to remove heat from the processor to maintain its operating temperature. Power - the main parameter of the cooler - shows how much heat it can take away from the processor.";
		}
	}
</script>