config/routes.rb
Rails.application.routes.draw do
  get 'hardware/cpu', to: "hardware#cpu", as: 'cpu_mod'
  get 'hardware/gpu', to: "hardware#gpu", as: 'gpu_mod'
  get 'hardware/motherboard', to: "hardware#motherboard", as: 'motherboard_mod'
  get 'hardware/memory', to: "hardware#memory", as: 'memory_mod'
  get 'hardware/psu', to: "hardware#psu", as: 'psu_mod'
  get 'hardware/disk', to: "hardware#disk", as: 'disk_mod'
  get 'hardware/cooler', to: "hardware#cooler", as: 'cooler_mod'
  get 'foradmin/manip_users'
  get 'foradmin/manip_hardware', to: "foradmin#manip_hardware", as: 'manip_hardware'
  devise_for :users
  get 'pages/welcome'
  get 'pages/configuration', to: "pages#configuration", as: 'configurator'
  get 'pages/observation', to: "pages#observation", as: 'observation'
  delete "pages/delete_pc/:id", to: "pages#delete_pc", as: 'delete_pc'
  delete "foradmin/delete_user/:id", to: "foradmin#delete_user", as: 'delete_user'
  post 'hardware/cpu', to: 'hardware#create_cpu', as: 'create_cpu'
  delete "hardware/delete_cpu/:id", to: "hardware#delete_cpu", as: 'delete_cpu'
  post 'hardware/gpu', to: 'hardware#create_gpu', as: 'create_gpu'
  delete "hardware/delete_gpu/:id", to: "hardware#delete_gpu", as: 'delete_gpu'
  post 'hardware/motherboard', to: 'hardware#create_motherboard', as: 'create_motherboard'
  delete "hardware/delete_motherboard/:id", to: "hardware#delete_motherboard", as: 'delete_motherboard'
  post 'hardware/memory', to: 'hardware#create_memory', as: 'create_memory'
  delete "hardware/delete_memory/:id", to: "hardware#delete_memory", as: 'delete_memory'
  post 'hardware/psu', to: 'hardware#create_psu', as: 'create_psu'
  delete "hardware/delete_psu/:id", to: "hardware#delete_psu", as: 'delete_psu'
  post 'hardware/disk', to: 'hardware#create_disk', as: 'create_disk'
  delete "hardware/delete_disk/:id", to: "hardware#delete_disk", as: 'delete_disk'
  post 'hardware/cooler', to: 'hardware#create_cooler', as: 'create_cooler'
  delete "hardware/delete_cooler/:id", to: "hardware#delete_cooler", as: 'delete_cooler'
  post "pages/configuration", to: "pages#creation"
  get "pages/show_pc/:id", to: "pages#show_pc", as: 'show_pc'
  patch "pages/ru", to: "pages#ru", as: 'ru'
  patch "pages/eng", to: "pages#en", as: 'eng'
  get "pages/send_computers", to: "pages#send_computers", as: 'comp_mail'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#welcome"
end

app/controllers/hardware_controller.rb
# frozen_string_literal: true

# Контроллер для управления комплектующими в БД
class HardwareController < ApplicationController
  def cpu
    @cpus = Cpu.all
  end

  def gpu
    @gpus = Videocard.all
  end

  def motherboard
    @mbs = Motherboard.all
  end

  def memory
    @memories = Memory.all
  end

  def psu
    @psus = Psu.all
  end

  def disk
    @disks = Disk.all
  end

  def cooler
    @coolers = Cooler.all
  end

  def cpu_params
    params.permit(:manufact, :socket, :model, :core_num, :tdp, :price)
  end

  def cpu_blank_check
    params[:manufact].blank? || params[:socket].blank? || params[:model].blank?
  end

  def create_cpu
    return if cpu_blank_check || params[:core_num].to_i < 1 || params[:tdp].to_i < 1 || params[:price].to_i < 1

    Cpu.create(cpu_params)
    redirect_to cpu_mod_path
  end

  def delete_cpu
    @cpu = Cpu.find(params[:id])
    @cpu.destroy
    redirect_to cpu_mod_path
  end

  def gpu_params
    params.permit(:manufact, :model, :gen, :volume, :price)
  end

  def create_gpu
    return if params[:manufact].blank? || params[:model].blank? || params[:gen].to_i < 1 || params[:volume].to_i < 1 || params[:price].to_i < 1

    Videocard.create(gpu_params)
    redirect_to gpu_mod_path
  end

  def delete_gpu
    @gpu = Videocard.find(params[:id])
    @gpu.destroy
    redirect_to gpu_mod_path
  end

  def motherboard_params
    params.permit(:name, :socket, :chipset, :price, :memory_slots)
  end

  def create_motherboard
    return if params[:name].blank? || params[:socket].blank? || params[:chipset].blank? || params[:price].to_i < 1 || params[:memory_slots].to_i < 1

    Motherboard.create(motherboard_params)
    redirect_to motherboard_mod_path
  end

  def delete_motherboard
    @mb = Motherboard.find(params[:id])
    @mb.destroy
    redirect_to motherboard_mod_path
  end

  def memory_params
    params.permit(:volume_one, :max_freq, :price)
  end

  def create_memory
    return if params[:volume_one].to_i < 1 || params[:max_freq].to_i < 1 || params[:price].to_i < 1

    Memory.create(memory_params)
    redirect_to memory_mod_path
  end

  def delete_memory
    @memory = Memory.find(params[:id])
    @memory.destroy
    redirect_to memory_mod_path
  end

  def psu_params
    params.permit(:wattage, :certificate, :price)
  end

  def create_psu
    return if params[:wattage].to_i < 1 || params[:certificate].blank? || params[:price].to_i < 1

    Psu.create(psu_params)
    redirect_to psu_mod_path
  end

  def delete_psu
    @psu = Psu.find(params[:id])
    @psu.destroy
    redirect_to psu_mod_path
  end

  def disk_params
    params.permit(:storage_type, :volume, :price)
  end

  def create_disk
    return if params[:storage_type].blank? || params[:volume].to_i < 1 || params[:price].to_i < 1

    Disk.create(disk_params)
    redirect_to disk_mod_path
  end

  def delete_disk
    @disk = Disk.find(params[:id])
    @disk.destroy
    redirect_to disk_mod_path
  end

  def cooler_params
    params.permit(:socket, :tdp, :price)
  end

  def create_cooler
    return if params[:socket].blank? || params[:tdp].to_i < 1 || params[:price].to_i < 1

    Cooler.create(cooler_params)
    redirect_to cooler_mod_path
  end

  def delete_cooler
    @cooler = Cooler.find(params[:id])
    @cooler.destroy
    redirect_to cooler_mod_path
  end
end

app/helpers/hardware_helper.rb
module HardwareHelper
end

app/views/hardware/cooler.html.erb
<div style="background-image: url(https://i.pinimg.com/originals/1f/3d/85/1f3d85148ab183f085a42b5649069499.jpg); height: 996px;">
	<div class="hardwareheader" ><h1 style="padding-top: 25px; font-size: 40px;"><%= t :coolers %></h1></div>
	<div class="hardleftsidebar"></div>
	<div style="float: left;">
		<table class="hardwaretable">
		  <thead>
		    <tr>
		      	<th><%= t :socket %></th>
				<th><%= t :tdp %></th>
				<th><%= t :price %></th>
		      	<th></th>
		    </tr>
		  </thead>
		  <tbody>
		    <% @coolers.each do |x| %>
		      <tr>
		          <td><%= x.socket %></td>
		          <td><%= x.tdp %></td>
		          <td><%= x.price %></td>
		          <td><%= button_to t(:delete), delete_cooler_path(x), method: :delete %></td>
		      </tr>
		    <% end %>
		  </tbody>
		</table>
	</div>
	<div class="creationform">
		<h1 class="formheader"><%= t :add_cooler %></h1>
		<%= form_with do |form| %>
			<%= form.label t(:socket), :class => "formlabel" %></br>
			<%= form.text_field :socket, :class => "forminput" %></br>
			<%= form.label t(:wattage), :class => "formlabel" %></br>
			<%= form.text_field :tdp, :class => "forminput" %></br>
			<%= form.label t(:price), :class => "formlabel" %></br>
			<%= form.text_field :price, :class => "forminput" %></br>
			<%= form.submit t(:add), :class => "formsubmit" %></br>
		<% end %>
	</div>
	<div class="hardrightsidebar"><%= button_to t(:back), manip_hardware_path, method: :get, :class => "rightsidebarlinks", :style => "margin-left: 64px;" %></div>
</div>

app/views/hardware/cpu.html.erb
<div style="background-image: url(https://i.pinimg.com/originals/1f/3d/85/1f3d85148ab183f085a42b5649069499.jpg); height: 996px;">
	<div class="hardwareheader" ><h1 style="padding-top: 25px; font-size: 40px;"><%= t :cpus %></h1></div>
	<div class="hardleftsidebar"></div>
	<div style="float: left;">
		<table class="hardwaretable">
		  <thead>
		    <tr>
		      	<th><%= t :manufact %></th>
		      	<th><%= t :socket %></th>
		      	<th><%= t :model %></th>
				<th><%= t :core_num %></th>
				<th><%= t :tdp %></th>
				<th><%= t :price %></th>
		      	<th></th>
		    </tr>
		  </thead>
		  <tbody>
		    <% @cpus.each do |x| %>
		      <tr>
		          <td><%= x.manufact %></td>
		          <td><%= x.socket %></td>
		          <td><%= x.model %></td>
		          <td><%= x.core_num %></td>
		          <td><%= x.tdp %></td>
		          <td><%= x.price %></td>
		          <td><%= button_to t(:delete), delete_cpu_path(x), method: :delete %></td>
		      </tr>
		    <% end %>
		  </tbody>
		</table>
	</div>
	<div class="creationform">
		<h1 class="formheader"><%= t :add_cpu %></h1>
		<%= form_with do |form| %>
			<%= form.label t(:manufact), :class => "formlabel" %></br>
			<%= form.text_field :manufact, :class => "forminput" %></br>
			<%= form.label t(:socket), :class => "formlabel" %></br>
			<%= form.text_field :socket, :class => "forminput" %></br>
			<%= form.label t(:model), :class => "formlabel" %></br>
			<%= form.text_field :model, :class => "forminput" %></br>
			<%= form.label t(:core_num), :class => "formlabel" %></br>
			<%= form.text_field :core_num, :class => "forminput" %></br>
			<%= form.label t(:tdp), :class => "formlabel" %></br>
			<%= form.text_field :tdp, :class => "forminput" %></br>
			<%= form.label t(:price), :class => "formlabel" %></br>
			<%= form.text_field :price, :class => "forminput" %></br>
			<%= form.submit t(:add), :class => "formsubmit" %></br>
		<% end %>
	</div>
	<div class="hardrightsidebar"><%= button_to t(:back), manip_hardware_path, method: :get, :class => "rightsidebarlinks", :style => "margin-left: 64px;" %></div>
</div>

app/views/hardware/disk.html.erb
<div style="background-image: url(https://i.pinimg.com/originals/1f/3d/85/1f3d85148ab183f085a42b5649069499.jpg); height: 996px;">
	<div class="hardwareheader" ><h1 style="padding-top: 25px; font-size: 40px;"><%= t :disks %></h1></div>
	<div class="hardleftsidebar"></div>
	<div style="float: left;">
		<table class="hardwaretable">
		  <thead>
		    <tr>
		      	<th><%= t :store_type %></th>
		      	<th><%= t :volume %></th>
				<th><%= t :price %></th>
		      	<th></th>
		    </tr>
		  </thead>
		  <tbody>
		    <% @disks.each do |x| %>
		      <tr>
		          <td><%= x.storage_type %></td>
		          <td><%= x.volume %></td>
		          <td><%= x.price %></td>
		          <td><%= button_to t(:delete), delete_disk_path(x), method: :delete %></td>
		      </tr>
		    <% end %>
		  </tbody>
		</table>
	</div>
	<div class="creationform">
		<h1 class="formheader"><%= t :add_disk %></h1>
		<%= form_with do |form| %>
			<%= form.label t(:store_type), :class => "formlabel" %></br>
			<%= form.text_field :storage_type, :class => "forminput" %></br>
			<%= form.label t(:volume), :class => "formlabel" %></br>
			<%= form.text_field :volume, :class => "forminput" %></br>
			<%= form.label t(:price), :class => "formlabel" %></br>
			<%= form.text_field :price, :class => "forminput" %></br>
			<%= form.submit t(:add), :class => "formsubmit" %></br>
		<% end %>
	</div>
	<div class="hardrightsidebar"><%= button_to t(:back), manip_hardware_path, method: :get, :class => "rightsidebarlinks", :style => "margin-left: 64px;" %></div>
</div>

app/views/hardware/gpu.html.erb
<div style="background-image: url(https://i.pinimg.com/originals/1f/3d/85/1f3d85148ab183f085a42b5649069499.jpg); height: 996px;">
	<div class="hardwareheader" ><h1 style="padding-top: 25px; font-size: 40px;"><%= t :gpus %></h1></div>
	<div class="hardleftsidebar"></div>
	<div style="float: left;">
		<table class="hardwaretable">
		  <thead>
		    <tr>
		      	<th><%= t :manufact %></th>
		      	<th><%= t :model %></th>
		      	<th><%= t :gen %></th>
				<th><%= t :volume %></th>
				<th><%= t :price %></th>
		      	<th></th>
		    </tr>
		  </thead>
		  <tbody>
		    <% @gpus.each do |x| %>
		      <tr>
		          <td><%= x.manufact %></td>
		          <td><%= x.model %></td>
		          <td><%= x.gen %></td>
		          <td><%= x.volume %></td>
		          <td><%= x.price %></td>
		          <td><%= button_to t(:delete), delete_gpu_path(x), method: :delete %></td>
		      </tr>
		    <% end %>
		  </tbody>
		</table>
	</div>
	<div class="creationform">
		<h1 class="formheader"><%= t :add_gpu %></h1>
		<%= form_with do |form| %>
			<%= form.label t(:manufact), :class => "formlabel" %></br>
			<%= form.text_field :manufact, :class => "forminput" %></br>
			<%= form.label t(:model), :class => "formlabel" %></br>
			<%= form.text_field :model, :class => "forminput" %></br>
			<%= form.label t(:gen), :class => "formlabel" %></br>
			<%= form.text_field :gen, :class => "forminput" %></br>
			<%= form.label t(:volume), :class => "formlabel" %></br>
			<%= form.text_field :volume, :class => "forminput" %></br>
			<%= form.label t(:price), :class => "formlabel" %></br>
			<%= form.text_field :price, :class => "forminput" %></br>
			<%= form.submit t(:add), :class => "formsubmit" %></br>
		<% end %>
	</div>
	<div class="hardrightsidebar"><%= button_to t(:back), manip_hardware_path, method: :get, :class => "rightsidebarlinks", :style => "margin-left: 64px;" %></div>
</div>

app/views/hardware/memory.html.erb
<div style="background-image: url(https://i.pinimg.com/originals/1f/3d/85/1f3d85148ab183f085a42b5649069499.jpg); height: 996px;">
	<div class="hardwareheader" ><h1 style="padding-top: 25px; font-size: 40px;"><%= t :memories %></h1></div>
	<div class="hardleftsidebar"></div>
	<div style="float: left;">
		<table class="hardwaretable">
		  <thead>
		    <tr>
		      	<th><%= t :vol_one %></th>
		      	<th><%= t :freq %></th>
				<th><%= t :price %></th>
		      	<th></th>
		    </tr>
		  </thead>
		  <tbody>
		    <% @memories.each do |x| %>
		      <tr>
		          <td><%= x.volume_one %></td>
		          <td><%= x.max_freq %></td>
		          <td><%= x.price %></td>
		          <td><%= button_to t(:delete), delete_memory_path(x), method: :delete %></td>
		      </tr>
		    <% end %>
		  </tbody>
		</table>
	</div>
	<div class="creationform">
		<h1 class="formheader"><%= t :add_mem %></h1>
		<%= form_with do |form| %>
			<%= form.label t(:vol_one), :class => "formlabel" %></br>
			<%= form.text_field :volume_one, :class => "forminput" %></br>
			<%= form.label t(:freq), :class => "formlabel" %></br>
			<%= form.text_field :max_freq, :class => "forminput" %></br>
			<%= form.label t(:price), :class => "formlabel" %></br>
			<%= form.text_field :price, :class => "forminput" %></br>
			<%= form.submit t(:add), :class => "formsubmit" %></br>
		<% end %>
	</div>
	<div class="hardrightsidebar"><%= button_to t(:back), manip_hardware_path, method: :get, :class => "rightsidebarlinks", :style => "margin-left: 64px;" %></div>
</div>

app/views/hardware/motherboard.html.erb
<div style="background-image: url(https://i.pinimg.com/originals/1f/3d/85/1f3d85148ab183f085a42b5649069499.jpg); height: 996px;">
	<div class="hardwareheader" ><h1 style="padding-top: 25px; font-size: 40px;"><%= t :motherboards %></h1></div>
	<div class="hardleftsidebar"></div>
	<div style="float: left;">
		<table class="hardwaretable">
		  <thead>
		    <tr>
		    	<th><%= t :name %></th>
		      	<th><%= t :socket %></th>
		      	<th><%= t :chipset %></th>
				<th><%= t :slots_num %></th>
				<th><%= t :price %></th>
		      	<th></th>
		    </tr>
		  </thead>
		  <tbody>
		    <% @mbs.each do |x| %>
		      <tr> 
		      	  <td><%= x.name %></td>	
		          <td><%= x.socket %></td>
		          <td><%= x.chipset %></td>
		          <td><%= x.memory_slots %></td>
		          <td><%= x.price %></td>
		          <td><%= button_to t(:delete), delete_motherboard_path(x), method: :delete %></td>
		      </tr>
		    <% end %>
		  </tbody>
		</table>
	</div>
	<div class="creationform">
		<h1 class="formheader"><%= t :add_mb %></h1>
		<%= form_with do |form| %>
			<%= form.label t(:name), :class => "formlabel" %></br>
			<%= form.text_field :name, :class => "forminput" %></br>
			<%= form.label t(:socket), :class => "formlabel" %></br>
			<%= form.text_field :socket, :class => "forminput" %></br>
			<%= form.label t(:chipset), :class => "formlabel" %></br>
			<%= form.text_field :chipset, :class => "forminput" %></br>
			<%= form.label t(:slots_num), :class => "formlabel" %></br>
			<%= form.text_field :memory_slots, :class => "forminput" %></br>
			<%= form.label t(:price), :class => "formlabel" %></br>
			<%= form.text_field :price, :class => "forminput" %></br>
			<%= form.submit t(:add), :class => "formsubmit" %></br>
		<% end %>
	</div>
	<div class="hardrightsidebar"><%= button_to t(:back), manip_hardware_path, method: :get, :class => "rightsidebarlinks", :style => "margin-left: 64px;" %></div>
</div>

app/views/hardware/psu.html.erb
<div style="background-image: url(https://i.pinimg.com/originals/1f/3d/85/1f3d85148ab183f085a42b5649069499.jpg); height: 996px;">
	<div class="hardwareheader" ><h1 style="padding-top: 25px; font-size: 40px;"><%= t :psus %></h1></div>
	<div class="hardleftsidebar"></div>
	<div style="float: left;">
		<table class="hardwaretable">
		  <thead>
		    <tr>
		      	<th><%= t :wattage %></th>
		      	<th><%= t :certif %></th>
		      	<th><%= t :price %></th>
		      	<th></th>
		    </tr>
		  </thead>
		  <tbody>
		    <% @psus.each do |x| %>
		      <tr>
		          <td><%= x.wattage %></td>
		          <td><%= x.certificate %></td>
		          <td><%= x.price %></td>
		          <td><%= button_to t(:delete), delete_psu_path(x), method: :delete %></td>
		      </tr>
		    <% end %>
		  </tbody>
		</table>
	</div>
	<div class="creationform">
		<h1 class="formheader"><%= t :add_psu %></h1>
		<%= form_with do |form| %>
			<%= form.label t(:wattage), :class => "formlabel" %></br>
			<%= form.text_field :wattage, :class => "forminput" %></br>
			<%= form.label t(:certif), :class => "formlabel" %></br>
			<%= form.text_field :certificate, :class => "forminput" %></br>
			<%= form.label t(:price), :class => "formlabel" %></br>
			<%= form.text_field :price, :class => "forminput" %></br>
			<%= form.submit t(:add), :class => "formsubmit" %></br>
		<% end %>
	</div>
	<div class="hardrightsidebar"><%= button_to t(:back), manip_hardware_path, method: :get, :class => "rightsidebarlinks", :style => "margin-left: 64px;" %></div>
</div>